### ISSUE TITLE
Update precipitation heatmap to include dropdown button for year

### ISSUE THREAD

**Issue by mphemming** [oceanhackweek/ohw24_proj_MessageMeWhenItsHot_the_MHW_Vis-Report_app_au#30]

**Comment by JasonUWA** [comment]
### Task Completed

- [x] Added rainfall heatmap files (`rainfall_heatmap2004-2024.html`, `rainfall_heatmap2004-2024.json`) to the repository.
- [x] Updated notebook `rainfall-click 2004-2024.ipynb` with the latest analysis.

This task is now complete, closing this issue.

Closes #123
