### ISSUE TITLE
Temperature distribution plot

### ISSUE THREAD

**Issue by ribeiron** [oceanhackweek/ohw24_proj_MessageMeWhenItsHot_the_MHW_Vis-Report_app_au#8]

**Comment by ribeiron** [comment]
Distribution of temperatures typical for the time of year, can be defined as a seven day window either side of the date of interest as it is on isithotrightnow or different, if you have reasoning for the change. 

![Image](https://github.com/user-attachments/assets/7e56365c-c092-4036-9fac-a0a293e12ec9)

**Comment by bui83** [comment]
![Temperature_Distribution](https://github.com/user-attachments/assets/f207e700-f75b-45f6-ba1c-11735ba01f7a)

**Comment by bui83** [comment]
file is saved as png
